spring.application.name=hisami

# CHANGE IT TO THE CORRECT DATABSE
spring.datasource.url=jdbc:postgresql://localhost:5432/HisamiDB
spring.datasource.username=ikuyorih9
spring.datasource.password=hugonakamura
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Criar/atualizar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update  

# Mostrar SQL no console (bom para debug)
spring.jpa.show-sql=true  
spring.jpa.properties.hibernate.format_sql=true
