spring.application.name=hisami

spring.datasource.url=jdbc:postgresql://hisami.c478g6kmadjv.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=ikuyorih9
spring.datasource.password=ikuyorih9
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Criar/atualizar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update  

# Mostrar SQL no console (bom para debug)
spring.jpa.show-sql=true  
spring.jpa.properties.hibernate.format_sql=true
