spring.application.name=hisami

spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.SQL=DEBUG



# CHANGE IT TO THE CORRECT DATABSE
spring.datasource.url=jdbc:postgresql://localhost:5432/HisamiDB
spring.datasource.username=ikuyorih9
spring.datasource.password=ikuyorih9
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Criar/atualizar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update 

# Mostrar SQL no console (bom para debug)
spring.jpa.show-sql=true  
spring.jpa.properties.hibernate.format_sql=true

app.oauth2.client-id=${OAUTH_CLIENT_ID:hisami}
app.oauth2.redirect-uri=${OAUTH_REDIRECT_URI:http://localhost:4200}
app.oauth2.post-logout-redirect-uri=${OAUTH_POST_LOGOUT_REDIRECT_URI:http://localhost:4200}
