CREATE TABLE EMPLOYEE_ROLE(
    name VARCHAR(32),
    description VARCHAR(255),
    can_sell BOOLEAN NOT NULL,
    can_edit_menu BOOLEAN NOT NULL,
    can_change_roles BOOLEAN NOT NULL,
    CONSTRAINT PK_EMPLOYEE_ROLE PRIMARY KEY (name)
);

CREATE TABLE EMPLOYEE(
    cpf VARCHAR(11) NOT NULL,
    name VARCHAR(128) NOT NULL,
    salary FLOAT NOT NULL DEFAULT 0.0,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (cpf)
);

CREATE TABLE EMPLOYEE_ACCOUNT(
    username VARCHAR(32) NOT NULL,
    email VARCHAR(64) NOT NULL,
    password VARCHAR(256) NOT NULL,
    role VARCHAR(32) NOT NULL,
    CONSTRAINT PK_EMPLOYEE_ACCOUNT PRIMARY KEY (username),
    CONSTRAINT SK_EMPLOYEE_ACCOUNT UNIQUE (email),
    CONSTRAINT FK_EMPLOYEE_ACCOUNT FOREIGN KEY (role) REFERENCES EMPLOYEE_ROLE(name)
);

CREATE TABLE HAS_ACCOUNT(
    employee_cpf VARCHAR(11),
    employee_username VARCHAR(32),  
    CONSTRAINT PK_HAS_ACCOUNT PRIMARY KEY (employee_cpf, employee_username),
    CONSTRAINT FK1_HAS_ACCOUNT FOREIGN KEY (employee_cpf) REFERENCES EMPLOYEE(cpf),
    CONSTRAINT FK2_HAS_ACCOUNT FOREIGN KEY (employee_username) REFERENCES EMPLOYEE_ACCOUNT(username)
);