CREATE TABLE IF NOT EXISTS EMPLOYEE_ROLE(
    name VARCHAR(32),
    description VARCHAR(255),
    can_sell BOOLEAN NOT NULL,
    can_edit_menu BOOLEAN NOT NULL,
    can_change_roles BOOLEAN NOT NULL,
    can_register_employee BOOLEAN NOT NULL,
    CONSTRAINT PK_EMPLOYEE_ROLE PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE(
    cpf VARCHAR(11) NOT NULL,
    name VARCHAR(128) NOT NULL,
    salary FLOAT NOT NULL DEFAULT 0.0,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (cpf)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_ACCOUNT(
    username VARCHAR(32) NOT NULL,
    email VARCHAR(64) NOT NULL,
    password VARCHAR(256) NOT NULL,
    role VARCHAR(32) NOT NULL,
    init_date DATE NOT NULL,
    end_date DATE,
    CONSTRAINT PK_EMPLOYEE_ACCOUNT PRIMARY KEY (username),
    CONSTRAINT SK_EMPLOYEE_ACCOUNT UNIQUE (email),
    CONSTRAINT FK_EMPLOYEE_ACCOUNT FOREIGN KEY (role) REFERENCES EMPLOYEE_ROLE(name)
);

CREATE TABLE IF NOT EXISTS HAS_ACCOUNT(
    employee_cpf VARCHAR(11),
    employee_username VARCHAR(32),  
    CONSTRAINT PK_HAS_ACCOUNT PRIMARY KEY (employee_cpf, employee_username),
    CONSTRAINT FK1_HAS_ACCOUNT FOREIGN KEY (employee_cpf) REFERENCES EMPLOYEE(cpf),
    CONSTRAINT FK2_HAS_ACCOUNT FOREIGN KEY (employee_username) REFERENCES EMPLOYEE_ACCOUNT(username)
);

CREATE TABLE IF NOT EXISTS CUSTOMER(
    id SERIAL,
    cpf VARCHAR(11),
    name VARCHAR(128),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (id),
    CONSTRAINT SK_CUSTOMER UNIQUE (cpf)
);

CREATE TABLE IF NOT EXISTS PURCHASE(
    employee_cpf VARCHAR(11),
    customer_id INTEGER,
    date_time TIMESTAMP,
    CONSTRAINT PK_PURCHASE PRIMARY KEY (employee_cpf, customer_id, date_time)
);

CREATE TABLE IF NOT EXISTS PRODUCT(
    id SERIAL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512) NOT NULL,
    price_value FLOAT NOT NULL,
    price_unity VARCHAR(16) NOT NULL,
    barcode VARCHAR(32) UNIQUE NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS HAS_PRODUCTS(
    employee_cpf VARCHAR(11),
    customer_id INTEGER,
    date_time TIMESTAMP,
    product_id INTEGER,
    CONSTRAINT PK_HAS_PRODUCTS PRIMARY KEY (employee_cpf, customer_id, date_time, product_id),
    CONSTRAINT FK1_HAS_PRODUCTS FOREIGN KEY (employee_cpf, customer_id, date_time) REFERENCES PURCHASE(employee_cpf, customer_id, date_time),
    CONSTRAINT FK2_HAS_PRODUCTS FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
);

CREATE TABLE IF NOT EXISTS PRODUCT_HISTORY(
    employee_cpf VARCHAR(11),
    product_id INTEGER,
    changed_at TIMESTAMP,
    field_label VARCHAR(16) NOT NULL,
    field_old_value VARCHAR(16) NOT NULL,
    field_new_value VARCHAR(16) NOT NULL,
    CONSTRAINT PK_PRODUCT_HISTORY PRIMARY KEY (employee_cpf, product_id, changed_at),
    CONSTRAINT FK1_PRODUCT_HISTORY FOREIGN KEY (employee_cpf) REFERENCES EMPLOYEE(cpf),
    CONSTRAINT FK2_PRODUCT_HISTORY FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
);