CREATE TABLE IF NOT EXISTS EMPLOYEE_ROLE (
    name VARCHAR(32),
    description VARCHAR(255),
    can_sell BOOLEAN NOT NULL,
    can_edit_menu BOOLEAN NOT NULL,
    can_change_roles BOOLEAN NOT NULL,
    can_register_employee BOOLEAN NOT NULL,
    CONSTRAINT PK_EMPLOYEE_ROLE PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
    cpf VARCHAR(11) NOT NULL,
    name VARCHAR(128) NOT NULL,
    salary FLOAT NOT NULL DEFAULT 0.0,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (cpf)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_ACCOUNT (
    username VARCHAR(32) NOT NULL,
    email VARCHAR(64) NOT NULL,
    password VARCHAR(256) NOT NULL,
    role VARCHAR(32) NOT NULL,
    init_date DATE NOT NULL,
    end_date DATE,
    CONSTRAINT PK_EMPLOYEE_ACCOUNT PRIMARY KEY (username),
    CONSTRAINT SK_EMPLOYEE_ACCOUNT UNIQUE (email),
    CONSTRAINT FK_EMPLOYEE_ACCOUNT_ROLE FOREIGN KEY (role) REFERENCES EMPLOYEE_ROLE (name)
);

CREATE TABLE IF NOT EXISTS HAS_ACCOUNT (
    employee_cpf VARCHAR(11) NOT NULL,
    employee_username VARCHAR(32) NOT NULL,
    CONSTRAINT PK_HAS_ACCOUNT PRIMARY KEY (
        employee_cpf,
        employee_username
    ),
    CONSTRAINT FK1_HAS_ACCOUNT FOREIGN KEY (employee_cpf) REFERENCES EMPLOYEE (cpf),
    CONSTRAINT FK2_HAS_ACCOUNT FOREIGN KEY (employee_username) REFERENCES EMPLOYEE_ACCOUNT (username)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    id SERIAL,
    name VARCHAR(128),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    id SERIAL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512) NOT NULL,
    price FLOAT NOT NULL,
    cust FLOAT NOT NULL,
    percent_cust_price FLOAT NOT NULL,
    barcode VARCHAR(32) UNIQUE NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    image BYTEA,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS NEW_ORDER (
    customer_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    date_time TIMESTAMP NOT NULL,
    date_time_close TIMESTAMP,
    CONSTRAINT PK_NEW_ORDER PRIMARY KEY (
        customer_id,
        product_id,
        date_time
    ),
    CONSTRAINT FK1_NEW_ORDER FOREIGN KEY (customer_id) REFERENCES CUSTOMER (id),
    CONSTRAINT FK2_NEW_ORDER FOREIGN KEY (product_id) REFERENCES PRODUCT (id)
);

CREATE TABLE IF NOT EXISTS SELL (
    employee_cpf VARCHAR(11) NOT NULL,
    product_id INTEGER NOT NULL,
    date_time TIMESTAMP NOT NULL,
    CONSTRAINT PK_SELL PRIMARY KEY (
        employee_cpf,
        product_id,
        date_time
    ),
    CONSTRAINT FK1_SELL FOREIGN KEY (employee_cpf) REFERENCES EMPLOYEE (cpf),
    CONSTRAINT FK2_SELL FOREIGN KEY (product_id) REFERENCES PRODUCT (id)
);

CREATE TABLE IF NOT EXISTS PRODUCT_HISTORY (
    employee_cpf VARCHAR(11) NOT NULL,
    product_id INTEGER NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    field_label VARCHAR(16) NOT NULL,
    field_old_value VARCHAR(16) NOT NULL,
    field_new_value VARCHAR(16) NOT NULL,
    CONSTRAINT PK_PRODUCT_HISTORY PRIMARY KEY (
        employee_cpf,
        product_id,
        changed_at
    ),
    CONSTRAINT FK1_PRODUCT_HISTORY FOREIGN KEY (employee_cpf) REFERENCES EMPLOYEE (cpf),
    CONSTRAINT FK2_PRODUCT_HISTORY FOREIGN KEY (product_id) REFERENCES PRODUCT (id)
);

CREATE TABLE IF NOT EXISTS RAW (
    name VARCHAR(128),
    cust FLOAT,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT PK_RAW PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS PRODUCT_CONTAIN_RAW (
    raw_name VARCHAR(128) NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER,
    CONSTRAINT PK_PRODUCT_CONTAIN_RAW PRIMARY KEY (raw_name, product_id),
    CONSTRAINT FK1_PRODUCT_CONTAIN_RAW FOREIGN KEY (raw_name) REFERENCES RAW (name),
    CONSTRAINT FK2_PRODUCT_CONTAIN_RAW FOREIGN KEY (product_id) REFERENCES PRODUCT (id)
);